- recipe/build.sh
- recipe/meta.yaml
Otherwise downstream users must also install boost runtime libraries (like libboost_filesystem.so)
> Link boost symbols statically

- recipe/meta.yaml
There are some API changes here, so I will update parquet-cpp after this goes in.
> Bump git hash and version number since we are after 0.1

- recipe/meta.yaml
This should also avoid the non-deterministic SHA issue
> Update to HEAD

- recipe/meta.yaml
The hope is that this will resolve the linker problem in https://github.com/conda-forge/pyarrow-feedstock/pull/33
> Update to include ARROW-1235 changes

- recipe/meta.yaml
Currently `arrow-cpp` can't be installed alongside `pytorch` on Windows because of the strict version pinning in this recipe.
`arrow-cpp` pins the `vc` package to *exactly* 14:
```
arrow-cpp 0.8.0 py36_vc14_3
---------------------------
dependencies:
numpy >=1.12
python 3.6*
snappy
vc 14
```
```
vc 14 h0510ff6_3
----------------
dependencies:
vs2015_runtime >=14.0.25123,<15.0a0
```
...whereas `pytorch` relies on the newer (but compatible) version 14.1:
```
vc 14.1 h21ff451_0
------------------
dependencies:
vs2017_runtime >=15.4.27004.2010,<16.0a0
```
IIUC this change should allow both packages to happily coexist in the same environment!
***Refs:***
* https://gitter.im/conda/conda?at=5a90356e35dd17022ee48639
* https://github.com/conda-forge/conda-forge.github.io/issues/537#issuecomment-368 …
> Relax pinning of vc package

- recipe/meta.yaml
In preparation for building this feedstock for aarch64 and ppc64le, bump the `numpy` minimum version to 1.16, which is the version we have built on those architectures. It was found to be too difficult to build earlier versions on those architectures; so, the minimum `numpy` version was bumped to the oldest version that could reasonably be built.
ref: https://github.com/conda-forge/numpy-feedstock/pull/136#issuecomment-510785440
Checklist
> Bump the NumPy pin in preparation for aarch64 and ppc64le builds

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/migrations/re220200601.yaml
- .github/CODEOWNERS
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/meta.yaml
Just as we are ignoring `run_exports` in `arrow-cpp`, we need to do the same in `pyarrow`. This is needed to ensure we do not pin `cudatoolkit` to `9.2`, but merely ensure `cudatoolkit` is at least `9.2`.
Checklist
Fixes https://github.com/conda-forge/arrow-cpp-feedstock/issues/149
> Ignore `run_exports` of `cudatoolkit` in `pyarrow`

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_ppc64le_boost_cpp1.72.0numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_boost_cpp1.72.0numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_boost_cpp1.72.0numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_boost_cpp1.72.0numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_boost_cpp1.74.0numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_ppc64le_boost_cpp1.74.0numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_boost_cpp1.74.0numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_boost_cpp1.74.0numpy1.19python3.9.____cpython.yaml
- .ci_support/migrations/aws_sdk_cpp1870.yaml
- .travis.yml
- README.md
- conda-forge.yml
- recipe/build-arrow.sh
- recipe/build-pyarrow.sh
Tentatively re-enable the ppc64le build, as suggested by @xhochy 
Checklist
> Add ppc64le to build

- conda-forge.yml
Currently in RAPIDS we are still on Arrow 1.0. Have run into segfaults when trying to upgrade to 4.0 ( https://github.com/rapidsai/cudf/pull/7495 ). Our most recent release is still on Arrow 1.0 for this reason. However there are some conflicts when installing (particularly around libthrift version 0.14.2). Try to resuscitate this branch to clear up those issues for users trying to install the last release.
<hr>
Checklist
> Readd `1.0.x` migrations

- recipe/meta.yaml
Checklist
Fixes #814. Adds abseil to the pyarrow host section to get it to properly parametrize on arrow-cpp build variants to prevent issues where we can't use certain abseil versions because pyarrow only pins to other version arrow-cpp builds.
> add abseil to pyarrow host section

- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl1.1.1python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl1.1.1python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.21openssl1.1.1python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.23openssl1.1.1python3.11.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/migrations/orc181.yaml
- .ci_support/osx_64_numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/osx_64_numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.23openssl3python3.11.____cpython.yaml
- recipe/meta.yaml
Looks like in the whole migration merging rerendering process the changes got lost in most of the builds.
cc @h-vetinari @jakirkham
Checklist
> [9.0.x] Fix ORC 1.8.1 migration

- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl1.1.1python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl1.1.1python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.21openssl1.1.1python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.23openssl1.1.1python3.11.____cpython.yaml
- .ci_support/linux_64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_versionNonecxx_compiler_version11numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/migrations/orc181.yaml
- .ci_support/osx_64_numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/osx_64_numpy1.23openssl3python3.11.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20openssl3python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.20openssl3python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21openssl3python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.23openssl3python3.11.____cpython.yaml
- recipe/meta.yaml
Looks like in the whole migration merging rerendering process the changes got lost in most of the builds.
cc @h-vetinari @jakirkham
Checklist
> [8.0.x] Fix ORC 1.8.1 migration

- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_sdk_cpp11057.yaml
- .ci_support/migrations/libgoogle_cloud270.yaml
- .ci_support/migrations/re220230201.yaml
- .ci_support/win_64_cuda_compiler_version10.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/build-arrow.sh
- recipe/meta.yaml
See https://github.com/conda-forge/arrow-cpp-feedstock/issues/962#issuecomment-1433172084
Checklist
> Remove ucx dependency for now

- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/libabseil20230125.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version10.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- conda-forge.yml
- recipe/meta.yaml
> [main] Rebuild for libabseil20230125

- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/orc183.yaml
- .ci_support/migrations/ucx1410.yaml
- recipe/build-arrow.sh
- recipe/meta.yaml
Undo https://github.com/conda-forge/arrow-cpp-feedstock/pull/963 now that https://github.com/conda-forge/ucx-split-feedstock/pull/111 has been merged. Includes https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4256
> Reinstate ucx support

- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_sdk_cpp19375.yaml
- .ci_support/migrations/cuda_112_ppc64le_aarch64.yaml
- .ci_support/migrations/ucx1410.yaml
- .ci_support/win_64_cuda_compiler_version10.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/bld-arrow.bat
- recipe/build-arrow.sh
- recipe/meta.yaml
Checklist
Based on the Post-release mailing list for ARROW 12.0.0:
https://lists.apache.org/thread/2stklo8dgpgn4dkq2lmvy4483jqcxzgx
Arrow Acero has been split into libarrow_acero for 12.0.0. We should enable it on conda.
See original arrow issue:
- https://github.com/apache/arrow/issues/15280
Closes #1039
> Be explicit about ARROW_ACERO; add tests; remove `use_local` in migrators 

- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_sdk_cpp19375.yaml
- .ci_support/migrations/cuda_112_ppc64le_aarch64.yaml
- .ci_support/migrations/libgoogle_cloud2100.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version10.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Not sure why migrator failed to open for these two branches (perhaps related again to ucx or the outdated migrations with `use_local`)
> [10.0.x] Rebuild for libgoogle_cloud2100 

- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_sdk_cpp19375.yaml
- .ci_support/migrations/cuda_112_ppc64le_aarch64.yaml
- .ci_support/migrations/libgoogle_cloud2100.yaml
- .ci_support/migrations/ucx1410.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version10.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Not sure why migrator failed to open for these two branches (perhaps related again to ucx or the outdated migrations with `use_local`)
> [11.0.x] Rebuild for libgoogle_cloud2100 

- recipe/activate.sh
- recipe/build-arrow.sh
- recipe/meta.yaml
I expect this to fix #1060.
Checklist
> Rework libarrow activate.sh with finer-grained checks and logging

- recipe/activate.sh
- recipe/meta.yaml
We were checking `CF_LIBARROW_ACTIVATE_LOGGING` without a default value. This led to failure under `set -u`. For original report from @plattenschieber, see <https://github.com/conda-forge/arrow-cpp-feedstock/pull/1065#issuecomment-1571699535>:
> We stumbled upon an issue in our ci which seems to be related to this PR, as yesterdays build seems fine and todays doesn't work anymore :sweat_smile:
> 
> ```
> Transaction finished
> /workspace/repo/.env/etc/conda/activate.d/libarrow_activate.sh: line 11: CF_LIBARROW_ACTIVATE_LOGGING: unbound variable
> ```
> 
> The only change I could see was in the build number of `pyarrow` 12.0.0 `libarrow 12.0.0 h96638e8_3_cpu` worked fine -> `libarrow 12.0.0 h96638e8_4_cpu` got error from above
Checklist
> Fix unbound variable in activate script

- recipe/meta.yaml
Test runs on aarch and ppc have been really crashy recently. Turns out they all point to the exact same tests (even though the error shown in azure implies otherwise):
```
test_memory.py ..............FEEEEE                                      [ 36%]
```
Let's just skip those. Also added a few tests that fail occasionally, but regularly enough to be annoying. There's also the occasional error on windows where something like `with tempfile.TemporaryDirectory() as tempdir2:` can fail upon resource destruction with:
```
E    PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\tmpdw6ktuts\\x\\part-0.arrow'
```
These however happen pretty much anywhere, and while very annoying, aren't really …
> Stabilize CI by skipping crashy/flaky tests

- recipe/meta.yaml
More debugging of persistent crashes on aarch + cuda in `test_dataset.py`
> [10.0.x] More fixes for crashy aarch+cuda CI

- recipe/meta.yaml
More debugging of persistent crashes on aarch + cuda in `test_dataset.py`
> [11.0.x] More fixes for crashy aarch+cuda CI

- recipe/meta.yaml
More debugging of persistent crashes on aarch + cuda in `test_dataset.py`
> [main] More fixes for crashy aarch+cuda CI

- recipe/meta.yaml
While 95788ef2abe7c088ecba83b1fce52201a523e987 worked for arrow 10 & 11, the merge of #1075 has now consistently failed 6 runs in a row (two in PR, 4 on main). Let's try again...
> Skip some more crashy tests on aarch+CUDA

- recipe/build-arrow.sh
- recipe/meta.yaml
> Allow 64kb pagesize on aarch64

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0203.yaml
- .ci_support/migrations/libgrpc154.yaml
- .ci_support/migrations/orc190.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- README.md
- conda-forge.yml
- recipe/build-arrow.sh
- recipe/build-pyarrow.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Closes #1114 with https://github.com/conda-forge/conda-smithy/pull/1747 (after various other approaches to increase space were not enough).
> Fix cross-compiled CUDA jobs that are running out of space

- recipe/activate.sh
- recipe/build-arrow.sh
- recipe/meta.yaml
Reinstate 7c0287a84ba8303b12c97e397f2b24a0239b6b46
Closes #1126
Also pick up some small improvements from #1124
> [main] bail out of activation if environment is not writable

- .ci_support/migrations/aws_crt_cpp0230.yaml
- conda-forge.yml
- recipe/meta.yaml
- recipe/patches/0001-GH-15017-Python-Harden-test_memory.py-for-use-with-A.patch
~Let's see what building off of the latest tag brings. This helps prepare for when the bot comes around, but also to button up https://github.com/apache/arrow/pull/35637~
For arrow 13 I'm also planning to remove the old naming of the outputs `arrow-cpp` & `arrow-cpp-proc`.
Closes #1139
> arrow 13.0.0

- recipe/meta.yaml
Pick up some changes from in-flight #1170; minio made it into conda-forge very recently, and `sparse` doesn't seem to cause segfaults anymore.
> Test dependencies expansion

- recipe/meta.yaml
- recipe/patches/0004-GH-38375-Python-Initialize-S3-on-first-use.patch
Checklist
This PR backports a critical fix from https://github.com/apache/arrow/pull/38375/ (which is expected to be released in Arrow 15.0.0) to Arrow 13.0.0 conda-forge packages. This patch helps pyarrow avoid triggering a bug in aws-sdk-cpp with S3 finalization that results in a segfault. Context:
- https://github.com/apache/arrow/pull/38375
- https://github.com/apache/arrow/issues/38364
- https://github.com/aws/aws-sdk-cpp/issues/2681
> Backport critical fix for S3 finalization from GH-38375.

- .ci_support/migrations/aws_crt_cpp0244.yaml
- .ci_support/migrations/aws_sdk_cpp111182.yaml
- recipe/meta.yaml
- recipe/patches/0002-GH-38364-Python-Initialize-S3-on-first-use-38375.patch
Checklist
Backport of https://github.com/conda-forge/arrow-cpp-feedstock/pull/1211 for Arrow 12 with [additional changes](https://github.com/conda-forge/arrow-cpp-feedstock/compare/12.x...pentschev:12.x-s3fs-init-on-use?expand=1#diff-114bea9fc3d55b1a0f06c35e540c16426d01cd2fd464cfbe03fcdb0ffb293db8R103-R144) required for Arrow < 13.
> [12.x] Backport critical fix for S3 finalization from GH-38375

- conda-forge.yml
- recipe/meta.yaml
> Update to v15.0.0

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0262.yaml
- .ci_support/migrations/aws_sdk_cpp111267.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Collected backport of
#1306 
#1307 
~#1308~ glog deferred due to https://github.com/conda-forge/glog-feedstock/issues/26
Waiting for builds from https://github.com/conda-forge/aws-sdk-cpp-feedstock/pull/842
> [12.x] Rebuild for aws_crt_cpp 0.26.2, aws_sdk_cpp 1.11.267

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0262.yaml
- .ci_support/migrations/aws_sdk_cpp111267.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Collected backport of
#1306 
#1307 
~#1308~ glog deferred due to https://github.com/conda-forge/glog-feedstock/issues/26
Waiting for builds from https://github.com/conda-forge/aws-sdk-cpp-feedstock/pull/842
> [13.x] Rebuild for aws_crt_cpp 0.26.2, aws_sdk_cpp 1.11.267

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_aarch64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_ppc64le_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_ppc64le_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/migrations/libgoogle_cloud217.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compilerNonecuda_compiler_versionNone.yaml
- .ci_support/win_64_cuda_compilernvcccuda_compiler_version11.2.yaml
- README.md
- conda-forge.yml
- recipe/conda_build_config.yaml
- recipe/meta.yaml
- recipe/patches/0001-fixture-teardown-should-not-fail-test.patch
- recipe/patches/0002-Revert-GH-37803-CI-Dev-Python-Release-and-merge-scri.patch
This needed a bunch of work on the google-cloud-cpp side (see [here](https://github.com/conda-forge/google-cloud-cpp-feedstock/issues/141)), but now we should hopefully be able to reap the benefits!
Closes #1305 
~Currently based on #1312, draft until that goes in.~
> Switch to more specific (=smaller) bindings for GCP

- .ci_support/linux_64_c_compiler_version10c_stdlib_version2.17cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_64_c_compiler_version12c_stdlib_version2.12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_aarch64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_ppc64le_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/migrations/aws_crt_cpp0268.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compilerNonecuda_compiler_versionNone.yaml
- .ci_support/win_64_cuda_compilernvcccuda_compiler_version11.2.yaml
- recipe/meta.yaml
Checklist
---
Closes https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/5815
The migration for [aws_crt_cpp 0.26.8](https://conda-forge.org/status/migration/aws_crt_cpp0268) failed for arrow-cpp-feedstock because the rerendering took longer than the limit of 900 seconds. I applied the migration locally.
> Rebuild for aws_crt_cpp 0.26.8

- recipe/meta.yaml
- recipe/patches/0001-C-CMake-correctly-use-Protobuf_PROTOC_EXECUTABLE.patch
- recipe/patches/0002-teach-CheckTimeZoneDatabaseAvailability-how-to-inspe.patch
Fix required for https://github.com/conda-forge/pyarrow-feedstock/pull/122
> don't fail tzdb availability check prematurely

- recipe/build.sh
- recipe/meta.yaml
- recipe/patches/0001-GH-44455-C-Update-vendored-date-to-3.0.3.patch
- recipe/patches/0002-GH-44448-C-Add-support-for-overriding-grpc_cpp_plugi.patch
This is a rebased version of #1432, where we tested the release including the python bits.
In particular, we need to fix two issues, for which the fixes did not get backported to the release:
* https://github.com/apache/arrow/issues/44448
* https://github.com/apache/arrow/issues/44455
This also fixes a long-standing inaccuracy in our builds (apparently CMake didn't think we're cross-compiling), and gets rid of the sed-hacks for the grpc_cpp_plugin 🥳 
Finally, we also fix #1425, as discussed in that issue.
PS. Let's hope that, unlike #1432, this doesn't run into https://github.com/conda-forge/conda-smithy/issues/2101
> libarrow v18.0.0

- recipe/activate.sh
- recipe/meta.yaml
Otherwise, the GDB symlinks will be included in packages built with libarrow as a host dependency.
Closes #1478
Checklist
> Bail on activation when CONDA_BUILD is set

- recipe/activate.sh
- recipe/meta.yaml
Fixes #1695
Follow-up to #1694
This proposes changing the condition `if [ -n "${CONDA_BUILD}" ]` to `if [ -n "${CONDA_BUILD:-}" ]` (adding a fallback to null), so that activating an environment with `libarrow` in it in a bash process with `-e -u` set does not fail.
I *think* this state still achieves the design goals of #1694.
Thanks for your time and consideration.
> add a fallback to null in CONDA_BUILD check

- .ci_support/linux_64_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_aarch64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_ppc64le_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_ppc64le_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/migrations/cuda118.yaml
- .ci_support/win_64_cuda_compiler_version11.8.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- build-locally.py
- recipe/meta.yaml
With the removal of CUDA 11.8 as a default version, our `cuda_compiler_version_min` will soon be 12.6 or even 12.9
Given that we have a custom migrator for the [express purpose](https://conda-forge.org/news/2025/05/29/cuda-118/) of staying on CUDA 11.8 where that's necessary or beneficial, and given that @kkraus14 has always advocated for keeping the lowest-possible bound in `__cuda >=X`, let's use this here.
~This currently uses fix-ups from https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7482 & https://github.com/conda-forge/conda-smithy/pull/2338 to work. Once those things have settled, I'm happy to backport this to the maintenance branches.~
> [main] Stay on CUDA 11.8
