conda-forge/arrow-cpp-feedstock

- recipe/meta.yaml
> Update to HEAD

- README.md
- recipe/meta.yaml
Rerendering to see if the numpy version updates.
> MNT: Re-rendered with conda-smithy 2.4.2

- recipe/meta.yaml
> Add @kou as maintainer

- .github/PULL_REQUEST_TEMPLATE.md
- recipe/meta.yaml
> Update to version 0.10.0

- .appveyor.yml
- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .azure-pipelines/build_steps.sh
- .azure-pipelines/run_docker_build.sh
- .travis.yml
- README.md
- azure-pipelines.yml
- recipe/meta.yaml
> MNT: Re-rendered with conda-smithy 3.2.2 and pinning 2018.12.12

- .ci_support/linux_c_compilergcccxx_compilergxxpython2.7.yaml
- .ci_support/linux_c_compilergcccxx_compilergxxpython3.6.yaml
- .ci_support/linux_c_compilergcccxx_compilergxxpython3.7.yaml
- .ci_support/linux_c_compilertoolchain_ccxx_compilertoolchain_cxxpython2.7.yaml
- .ci_support/linux_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.6.yaml
- .ci_support/linux_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.7.yaml
- .ci_support/osx_c_compilerclangcxx_compilerclangxxpython2.7.yaml
- .ci_support/osx_c_compilerclangcxx_compilerclangxxpython3.6.yaml
- .ci_support/osx_c_compilerclangcxx_compilerclangxxpython3.7.yaml
- .ci_support/osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython2.7.yaml
- .ci_support/osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.6.yaml
- .ci_support/osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.7.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015python3.6.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015python3.7.yaml
- recipe/meta.yaml
> MNT: Re-rendered with conda-smithy 3.2.2 and pinning 2019.01.09

- recipe/LLVM_LICENSE.txt
- recipe/meta.yaml
> LLVM license

- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/linux_python3.7.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/osx_python3.7.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015python3.6vc14.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015python3.7vc14.yaml
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
> Enable bz2 compression

- recipe/meta.yaml
> Tighten run_exports

- .ci_support/linux_python2.7.yaml
- .ci_support/linux_python3.6.yaml
- .ci_support/linux_python3.7.yaml
- .ci_support/linux_python3.8.yaml
- .ci_support/migrations/protobuf310.yaml
- .ci_support/osx_python2.7.yaml
- .ci_support/osx_python3.6.yaml
- .ci_support/osx_python3.7.yaml
- .ci_support/osx_python3.8.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015python3.6vc14.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015python3.7vc14.yaml
- .ci_support/win_c_compilervs2015cxx_compilervs2015python3.8vc14.yaml
- recipe/meta.yaml
> Manual migration for protobuf 3.10

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .drone.yml
- .github/CODEOWNERS
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/meta.yaml
@nealrichardson please approve
> Add Neal to the team

- .azure-pipelines/azure-pipelines-win.yml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- README.md
Hi! This is the friendly automated conda-forge-webservice.
I've rerendered the recipe as instructed in #151.
Here's a checklist to do before merging.
Fixes #151
> MNT: rerender

- recipe/meta.yaml
> Use snappy run_exports/dynamic linkage

- recipe/build-pyarrow.sh
- recipe/meta.yaml
> Remove redundant --with-cuda

- .ci_support/linux_aarch64_python3.6.____cpython.yaml
- .ci_support/linux_aarch64_python3.7.____cpython.yaml
- .ci_support/linux_aarch64_python3.8.____cpython.yaml
- .ci_support/linux_cuda_compiler_version9.2python3.6.____cpython.yaml
- .ci_support/linux_cuda_compiler_version9.2python3.7.____cpython.yaml
- .ci_support/linux_cuda_compiler_version9.2python3.8.____cpython.yaml
- .ci_support/linux_cuda_compiler_versionNonepython3.6.____cpython.yaml
- .ci_support/linux_cuda_compiler_versionNonepython3.7.____cpython.yaml
- .ci_support/linux_cuda_compiler_versionNonepython3.8.____cpython.yaml
- .ci_support/osx_python3.6.____cpython.yaml
- .ci_support/osx_python3.7.____cpython.yaml
- .ci_support/osx_python3.8.____cpython.yaml
- .ci_support/win_python3.6.____cpython.yaml
- .ci_support/win_python3.7.____cpython.yaml
- .ci_support/win_python3.8.____cpython.yaml
- recipe/meta.yaml
> Apache Arrow 1.0.0

- recipe/meta.yaml
> Drop pandas and six dependency

- recipe/meta.yaml
> Ensure that we have different build hashes

- .ci_support/migrations/aws_sdk_cpp1870.yaml
- recipe/8458.patch
- recipe/meta.yaml
This is part of `arrow-cpp` already.
Checklist
> Omit plasma server in pyarrow

- recipe/meta.yaml
Addresses https://github.com/conda-forge/arrow-cpp-feedstock/pull/195#issuecomment-719978175
FYI @conda-forge/help-osx-arm64 
Checklist
> Fix tests on osx-arm64

- recipe/build-arrow.sh
- recipe/meta.yaml
> Set correct pagesize for jemalloc on osx-arm64

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_boost_cpp1.72.0cuda_compiler_version9.2numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0cuda_compiler_version9.2numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0cuda_compiler_version9.2numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0cuda_compiler_version9.2numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0cuda_compiler_versionNonenumpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0cuda_compiler_versionNonenumpy1.16python3.7.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0cuda_compiler_versionNonenumpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.72.0cuda_compiler_versionNonenumpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0cuda_compiler_version9.2numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0cuda_compiler_version9.2numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0cuda_compiler_version9.2numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0cuda_compiler_version9.2numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0cuda_compiler_versionNonenumpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0cuda_compiler_versionNonenumpy1.16python3.7.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0cuda_compiler_versionNonenumpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_boost_cpp1.74.0cuda_compiler_versionNonenumpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_boost_cpp1.72.0numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_aarch64_boost_cpp1.72.0numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_aarch64_boost_cpp1.72.0numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_aarch64_boost_cpp1.72.0numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_boost_cpp1.74.0numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_aarch64_boost_cpp1.74.0numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_aarch64_boost_cpp1.74.0numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_aarch64_boost_cpp1.74.0numpy1.19python3.9.____cpython.yaml
- .ci_support/migrations/re220201101.yaml
- .drone.yml
- conda-forge.yml
> Set abi_migration_branches

- recipe/7df87aca022ab6a309a6ee515370686aa3bcc013.patch
- recipe/build-arrow.sh
- recipe/meta.yaml
> Fix osx-arm64 build

- .ci_support/osx_arm64_python3.8.____cpython.yaml
- .ci_support/osx_arm64_python3.9.____cpython.yaml
- recipe/build-arrow.sh
- recipe/meta.yaml
> Activate the alternative allocators on osx-arm64

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/migrations/windows_cuda.yaml
- .ci_support/win_64_cuda_compiler_version10.0numpy1.16python3.6.____cpython.yaml
- .ci_support/win_64_cuda_compiler_version10.0numpy1.16python3.7.____cpython.yaml
- .ci_support/win_64_cuda_compiler_version10.0numpy1.16python3.8.____cpython.yaml
- .ci_support/win_64_cuda_compiler_version10.0numpy1.19python3.9.____cpython.yaml
- .ci_support/win_64_cuda_compiler_versionNonenumpy1.16python3.6.____cpython.yaml
- .ci_support/win_64_cuda_compiler_versionNonenumpy1.16python3.7.____cpython.yaml
- .ci_support/win_64_cuda_compiler_versionNonenumpy1.16python3.8.____cpython.yaml
- .ci_support/win_64_cuda_compiler_versionNonenumpy1.19python3.9.____cpython.yaml
- README.md
- recipe/bld-arrow.bat
- recipe/bld-pyarrow.bat
- recipe/meta.yaml
Checklist
Not sure what's up with the bot having opened 3 PRs, but anyway, it's not smart enough for the specific skips here.
Closes #255
> Windows + Cuda

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_ppc64le_numpy1.16python3.6.____cpython.yaml
- .ci_support/migrations/windows_cuda.yaml
- .ci_support/win_64_cuda_compiler_version10.0numpy1.16python3.6.____cpython.yaml
- .ci_support/win_64_cuda_compiler_version10.0numpy1.16python3.7.____cpython.yaml
- .ci_support/win_64_cuda_compiler_version10.0numpy1.16python3.8.____cpython.yaml
- .ci_support/win_64_cuda_compiler_version10.0numpy1.19python3.9.____cpython.yaml
- .ci_support/win_64_cuda_compiler_versionNonenumpy1.16python3.6.____cpython.yaml
- .ci_support/win_64_cuda_compiler_versionNonenumpy1.16python3.7.____cpython.yaml
- .ci_support/win_64_cuda_compiler_versionNonenumpy1.16python3.8.____cpython.yaml
- .ci_support/win_64_cuda_compiler_versionNonenumpy1.19python3.9.____cpython.yaml
- README.md
- recipe/bld-arrow.bat
- recipe/bld-pyarrow.bat
- recipe/meta.yaml
Checklist
Cherry-picked the commits from #247 (aside from the rerender) into #263.
Closes #263
> Windows + Cuda [Branch 1.0.x]

- .ci_support/linux_64_cuda_compiler_version9.2numpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_version9.2numpy1.16python3.7.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_version9.2numpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_version9.2numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonenumpy1.16python3.6.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonenumpy1.16python3.7.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonenumpy1.16python3.8.____cpython.yaml
- .ci_support/linux_64_cuda_compiler_versionNonenumpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.16python3.6.____cpython.yaml
- recipe/build-arrow.sh
- recipe/build-pyarrow.sh
- recipe/meta.yaml
> Minor cleanups

- recipe/9569.patch
- recipe/meta.yaml
> Update patch 9569

- .ci_support/migrations/orc168.yaml
- recipe/meta.yaml
> arrow 4.0.1

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_64_numpy1.18python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.18python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/meta.yaml
> Pin aws-sdk-cpp at 1.8.186

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_64_numpy1.18python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.18python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- recipe/meta.yaml
> 3.0.x: Pin aws-sdk-cpp at 1.8.186

- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version7cuda_compiler_version10.2cxx_compiler_version7numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_64_c_compiler_version9cuda_compiler_versionNonecxx_compiler_version9numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_aarch64_numpy1.21python3.10.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.18python3.7.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.18python3.8.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.19python3.9.____cpython.yaml
- .ci_support/linux_ppc64le_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_64_numpy1.18python3.7.____cpython.yaml
- .ci_support/osx_64_numpy1.18python3.8.____cpython.yaml
- .ci_support/osx_64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_64_numpy1.21python3.10.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.8.____cpython.yaml
- .ci_support/osx_arm64_numpy1.19python3.9.____cpython.yaml
- .ci_support/osx_arm64_numpy1.21python3.10.____cpython.yaml
- recipe/meta.yaml
> 4.0.x: Pin aws-sdk-cpp at 1.8.186

- recipe/activate.sh
- recipe/meta.yaml
Checklist
resolves #946 
@h-vetinari let me know if any other change propagation is needed, I'm not very familiar with the branching setup in this repo.
> activate.sh: Perform read permission check before symlinking

- recipe/activate.sh
- recipe/meta.yaml
> [9.0.x] Backport activate.sh permission check

- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/libabseil20230125.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version10.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
> [10.0.x] Rebuild for libabseil20230125

- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0199.yaml
- .ci_support/migrations/libgrpc152.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- recipe/meta.yaml
- recipe/patches/0001-don-t-bake-non-relocatable-CMAKE_INSTALL_FULL_LIBDIR.patch
- recipe/patches/0002-GH-33882-C-Don-t-find-.pc-files-with-ARROW_BUILD_STA.patch
- recipe/patches/0003-GH-34404-Python-Failing-tests-because-pandas.Index-c.patch
- recipe/patches/0004-GH-15070-Python-CI-Compatibility-with-pandas-2.0-348.patch
- recipe/patches/0005-GH-34880-Python-CI-Fix-Windows-tests-failing-with-la.patch
- recipe/patches/0006-GH-15070-Python-CI-Update-pandas-test-for-empty-colu.patch
Bot failed:
```
linux_64_cuda_compiler_version10.2: Encountered problems while solving:
- package ucx-1.14.0-hcb274ce_0 has constraint cudatoolkit 10.2 conflicting with cudatoolkit-10.2.89-h713d32c_10
```
> [main] Rebuild for aws_crt_cpp0199

- .ci_support/linux_64_cuda_compiler_version10.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/libgrpc154.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version10.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
- recipe/patches/0001-don-t-bake-non-relocatable-CMAKE_INSTALL_FULL_LIBDIR.patch
- recipe/patches/0002-GH-33882-C-Don-t-find-.pc-files-with-ARROW_BUILD_STA.patch
- recipe/patches/0003-GH-34404-Python-Failing-tests-because-pandas.Index-c.patch
- recipe/patches/0004-GH-15070-Python-CI-Compatibility-with-pandas-2.0-348.patch
- recipe/patches/0005-GH-34880-Python-CI-Fix-Windows-tests-failing-with-la.patch
- recipe/patches/0006-GH-15070-Python-CI-Update-pandas-test-for-empty-colu.patch
- recipe/patches/0007-GH-34743-Python-Relax-condition-in-flaky-Flight-test.patch
Bot failed:
```
linux_64_cuda_compiler_version10.2: Encountered problems while solving:
- package ucx-1.14.0-h0aa22dc_1 has constraint cudatoolkit 10.2 conflicting with cudatoolkit-10.2.89-hfd86e86_0
```
> [main] Rebuild for libgrpc154

- recipe/activate.sh
- recipe/meta.yaml
> Make activation script more robust

- .ci_support/migrations/cuda120.yaml
- .ci_support/migrations/libgoogle_cloud2110.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- recipe/build-arrow.bat
- recipe/build-arrow.sh
- recipe/meta.yaml
Checklist
xref: https://github.com/conda-forge/arrow-cpp-feedstock/pull/1079
> Rebuild for CUDA 12 on 11.0.x

- .ci_support/migrations/cuda120.yaml
- .ci_support/migrations/libgoogle_cloud2110.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- recipe/build-arrow.bat
- recipe/build-arrow.sh
- recipe/meta.yaml
Checklist
xref: https://github.com/conda-forge/arrow-cpp-feedstock/pull/1079
> Rebuild for CUDA 12 on 10.0.x

- .ci_support/migrations/cuda120.yaml
- .ci_support/migrations/libgoogle_cloud2110.yaml
- recipe/bld-arrow.bat
- recipe/build-arrow.sh
- recipe/meta.yaml
Checklist
xref: https://github.com/conda-forge/arrow-cpp-feedstock/pull/1079
> Rebuild for CUDA 12 on 9.0.x

- recipe/build-arrow.sh
- recipe/meta.yaml
> Backport #1116 to v11.x

- recipe/build-arrow.sh
- recipe/meta.yaml
> Backport #1116 to v10.x

- recipe/build-arrow.sh
- recipe/meta.yaml
> Backport #1116 to v9.x

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0203.yaml
- .ci_support/migrations/libgrpc154.yaml
- .ci_support/migrations/orc190.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- README.md
- conda-forge.yml
- recipe/build-arrow.sh
- recipe/build-pyarrow.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> [11.0.x] Fix cross-compiled CUDA jobs that are running out of space

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0203.yaml
- .ci_support/migrations/libgrpc154.yaml
- .ci_support/migrations/orc190.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- README.md
- conda-forge.yml
- recipe/build-arrow.sh
- recipe/build-pyarrow.sh
- recipe/meta.yaml
> [10.0.x] Fix cross-compiled CUDA jobs that are running out of space

- recipe/activate.sh
- recipe/build-arrow.sh
- recipe/meta.yaml
> [10.0.x] bail out of activation if environment is not writable

- recipe/activate.sh
- recipe/build-arrow.sh
- recipe/meta.yaml
> [11.0.x] bail out of activation if environment is not writable

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/python312.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Try to short-circuit missing optional dependencies that block the bot.
> Rebuild for python312

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/cuda120.yaml
- .ci_support/migrations/libprotobuf4251.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- recipe/meta.yaml
The bot cannot open a PR because `cuda120.yaml` is broken as currently checked in.
> [13.x] Rebuild for grpc 1.60 & protobuf 4.25.1

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_aarch64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_ppc64le_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/migrations/aws_crt_cpp0260.yaml
- .ci_support/migrations/libprotobuf4251.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compilerNonecuda_compiler_versionNone.yaml
- .ci_support/win_64_cuda_compilernvcccuda_compiler_version11.2.yaml
- README.md
- recipe/meta.yaml
> [main] Rebuild for grpc 1.60 & protobuf 4.25.1

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0260.yaml
- .ci_support/migrations/aws_crt_cpp0261.yaml
- .ci_support/migrations/aws_sdk_cpp111242.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Bot seems to have given up now that the PR for main is in.
> [11.x] Rebuild for aws_crt_cpp 0.26.1 & aws_sdk_cpp 1.11.242

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0260.yaml
- .ci_support/migrations/aws_crt_cpp0261.yaml
- .ci_support/migrations/aws_sdk_cpp111242.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Bot seems to have given up now that the PR for main is in.
> [12.x] Rebuild for aws_crt_cpp 0.26.1 & aws_sdk_cpp 1.11.242

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0260.yaml
- .ci_support/migrations/aws_crt_cpp0261.yaml
- .ci_support/migrations/aws_sdk_cpp111242.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Bot seems to have given up now that the PR for main is in.
> [13.x] Rebuild for aws_crt_cpp 0.26.1 & aws_sdk_cpp 1.11.242

- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_aarch64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_ppc64le_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/migrations/aws_crt_cpp0261.yaml
- .ci_support/migrations/aws_sdk_cpp111242.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- README.md
- recipe/meta.yaml
Bot seems to have given up now that the PR for main is in.
> [14.x] Rebuild for aws_crt_cpp 0.26.1 & aws_sdk_cpp 1.11.242

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_aarch64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_ppc64le_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_ppc64le_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/migrations/aws_crt_cpp0262.yaml
- .ci_support/migrations/aws_sdk_cpp111267.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compilerNonecuda_compiler_versionNone.yaml
- .ci_support/win_64_cuda_compilernvcccuda_compiler_version11.2.yaml
- README.md
- recipe/meta.yaml
Collected backport of
#1306 
#1307 
~#1308~ glog deferred due to https://github.com/conda-forge/glog-feedstock/issues/26
> [14.x] Rebuild for aws_crt_cpp 0.26.2, aws_sdk_cpp 1.11.267

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_aarch64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_ppc64le_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/migrations/aws_sdk_cpp111267.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compilerNonecuda_compiler_versionNone.yaml
- .ci_support/win_64_cuda_compilernvcccuda_compiler_version11.2.yaml
- README.md
- recipe/install-libarrow.sh
- recipe/meta.yaml
@h-vetinari I would like to apply this on top of current PRs if you're happy with the change.
Closes #1307
> Preserve symlinks

- recipe/install-libarrow.sh
- recipe/meta.yaml
> 14.x: Preserve symlinks

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_aarch64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_ppc64le_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/migrations/aws_crt_cpp0262.yaml
- .ci_support/migrations/aws_sdk_cpp111242.yaml
- .ci_support/migrations/aws_sdk_cpp111267.yaml
- .ci_support/migrations/libgoogle_cloud217.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- README.md
- recipe/meta.yaml
> [14.x] Switch to more specific (=smaller) bindings for GCP

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0262.yaml
- .ci_support/migrations/aws_sdk_cpp111242.yaml
- .ci_support/migrations/aws_sdk_cpp111267.yaml
- .ci_support/migrations/libgoogle_cloud217.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
> [12.x] Switch to more specific (=smaller) bindings for GCP

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0261.yaml
- .ci_support/migrations/aws_crt_cpp0262.yaml
- .ci_support/migrations/aws_sdk_cpp111242.yaml
- .ci_support/migrations/aws_sdk_cpp111267.yaml
- .ci_support/migrations/libgoogle_cloud217.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
> [13.x] Switch to more specific (=smaller) bindings for GCP

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_c_compiler_version10cuda_compilernvcccuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_64_c_compiler_version12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_aarch64_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_ppc64le_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/migrations/glog07.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compilerNonecuda_compiler_versionNone.yaml
- .ci_support/win_64_cuda_compilernvcccuda_compiler_version11.2.yaml
- README.md
- recipe/meta.yaml
- recipe/patches/0001-fixture-teardown-should-not-fail-test.patch
- recipe/patches/0002-Support-glog-0.7.patch
> [14.x] Rebuild for glog 0.7

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/glog07.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
- recipe/patches/0001-GH-38263-C-Prefer-to-call-string_view-data-instead-o.patch
- recipe/patches/0002-GH-38364-Python-Initialize-S3-on-first-use-38375.patch
- recipe/patches/0003-Adaptations-for-Arrow-12.patch
- recipe/patches/0004-Support-glog-0.7.patch
> [12.x] Rebuild for glog 0.7

- recipe/meta.yaml
> Update to v15.0.1

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0264.yaml
- .ci_support/migrations/aws_crt_cpp0266.yaml
- .ci_support/migrations/orc200.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Not sure why the bot failed to open a PR
> [12.x] Rebuild for aws_crt_cpp 0.26.6

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0264.yaml
- .ci_support/migrations/aws_crt_cpp0266.yaml
- .ci_support/migrations/orc200.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Not sure why the bot failed to open a PR
> [13.x] Rebuild for aws_crt_cpp 0.26.6

- .ci_support/linux_64_cuda_compiler_version11.2.yaml
- .ci_support/linux_64_cuda_compiler_versionNone.yaml
- .ci_support/linux_aarch64_cuda_compiler_version11.2.yaml
- .ci_support/linux_aarch64_cuda_compiler_versionNone.yaml
- .ci_support/linux_ppc64le_cuda_compiler_version11.2.yaml
- .ci_support/linux_ppc64le_cuda_compiler_versionNone.yaml
- .ci_support/migrations/aws_crt_cpp0268.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.2.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- recipe/meta.yaml
Checklist
---
xref: https://github.com/conda-forge/arrow-cpp-feedstock/pull/1375 and https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/5815
cc: @h-vetinari
> [12.x] Rebuild for aws_crt_cpp 0.26.8

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_c_compiler_version10c_stdlib_version2.17cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_64_c_compiler_version12c_stdlib_version2.12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/linux_aarch64_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_aarch64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_ppc64le_c_compiler_version10cuda_compiler_version11.2cxx_compiler_version10.yaml
- .ci_support/linux_ppc64le_c_compiler_version12cuda_compiler_versionNonecxx_compiler_version12.yaml
- .ci_support/migrations/aws_crt_cpp0268.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compilerNonecuda_compiler_versionNone.yaml
- .ci_support/win_64_cuda_compilernvcccuda_compiler_version11.2.yaml
- README.md
- recipe/meta.yaml
Checklist
---
xref: https://github.com/conda-forge/arrow-cpp-feedstock/pull/1375 and https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/5815
cc: @h-vetinari
> [14.x] Rebuild for aws_crt_cpp 0.26.8

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_c_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_64_c_compiler_version13cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_aarch64_c_compiler_version13cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_ppc64le_c_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_ppc64le_c_compiler_version13cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/migrations/aws_crt_cpp0295.yaml
- .ci_support/migrations/aws_crt_cpp0296.yaml
- .ci_support/migrations/aws_crt_cpp0297.yaml
- .ci_support/migrations/aws_sdk_cpp111458.yaml
- .ci_support/migrations/libutf8proc29.yaml
- .ci_support/migrations/lz4_c110.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.8.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- README.md
- recipe/conda_build_config.yaml
- recipe/meta.yaml
A few migrations fell off the wagon for 15.x recently
> [15.x] migration catch-up

- .azure-pipelines/azure-pipelines-linux.yml
- .ci_support/linux_64_c_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_64_c_compiler_version13cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_aarch64_c_compiler_version13cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_ppc64le_c_compiler_version11cuda_compilernvcccuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_ppc64le_c_compiler_version13cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/migrations/aws_sdk_cpp111489.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_cuda_compiler_version11.8.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- README.md
- recipe/meta.yaml
Test https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6958 after #1673 had issues: https://github.com/conda-forge/aws-sdk-cpp-feedstock/issues/924
> [main] Rebuild for aws_sdk_cpp 1.11.489

- .ci_support/linux_64_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_aarch64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_ppc64le_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_ppc64le_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/migrations/cuda118.yaml
- .ci_support/win_64_cuda_compiler_version11.8.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- build-locally.py
- recipe/meta.yaml
> [17.x] Stay on CUDA 11.8 

- .ci_support/linux_64_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_aarch64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_ppc64le_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_ppc64le_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/migrations/cuda118.yaml
- .ci_support/win_64_cuda_compiler_version11.8.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- build-locally.py
- recipe/meta.yaml
> [19.x] Stay on CUDA 11.8

- .ci_support/linux_64_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_aarch64_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_aarch64_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/linux_ppc64le_c_compiler_version11cuda_compiler_version11.8cxx_compiler_version11.yaml
- .ci_support/linux_ppc64le_c_compiler_version13cuda_compiler_versionNonecxx_compiler_version13.yaml
- .ci_support/migrations/cuda118.yaml
- .ci_support/win_64_cuda_compiler_version11.8.yaml
- .ci_support/win_64_cuda_compiler_versionNone.yaml
- build-locally.py
- recipe/meta.yaml
> [18.x] Stay on CUDA 11.8
